module: Jetworking
author: JamitLabs
author_url: https://www.jamitlabs.com
root_url: https://jamitlabs.github.io/Jetworking/
github_url: https://github.com/JamitLabs/Jetworking
github_file_prefix: https://github.com/JamitLabs/Jetworking/tree/develop
swift_build_tool: spm
theme: fullwidth
clean: true
copyright: '© 2022 [JamitLabs](https://jamitlabs.com) under MIT.'

custom_categories:
  - name: Core Types
    children:
      - Client
      - Endpoint
  - name: Interceptors
    children:
      - AuthenticationInterceptor
      - HeaderFieldsInterceptor
      - LoggingInterceptor
